
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow_hr(object):
    def setupUi(self, loginWindow_hr):
        loginWindow_hr.setObjectName("loginWindow_hr")
        loginWindow_hr.resize(361, 285)
        self.centralwidget = QtWidgets.QWidget(loginWindow_hr)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 200, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 100, 189, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 140, 189, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 60, 189, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        loginWindow_hr.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(loginWindow_hr)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        loginWindow_hr.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(loginWindow_hr)
        self.statusbar.setObjectName("statusbar")
        loginWindow_hr.setStatusBar(self.statusbar)

        self.retranslateUi(loginWindow_hr)
        QtCore.QMetaObject.connectSlotsByName(loginWindow_hr)

    def retranslateUi(self, loginWindow_hr):
        _translate = QtCore.QCoreApplication.translate
        loginWindow_hr.setWindowTitle(_translate("loginWindow_hr", "MainWindow"))
        self.pushButton.setText(_translate("loginWindow_hr", "login in"))
        self.pushButton_2.setText(_translate("loginWindow_hr", "cancel"))
        self.label_3.setText(_translate("loginWindow_hr", "Enter E-Mail Id:"))
        self.label_2.setText(_translate("loginWindow_hr", "Enter HR ID:"))
        self.label_4.setText(_translate("loginWindow_hr", "Login In"))
        self.label_5.setText(_translate("loginWindow_hr", "Enter Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindow_hr = QtWidgets.QMainWindow()
    ui = Ui_loginWindow_hr()
    ui.setupUi(loginWindow_hr)
    loginWindow_hr.show()
    sys.exit(app.exec_())
