# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow_emp(object):
    def setupUi(self, loginWindow_emp):
        loginWindow_emp.setObjectName("loginWindow_emp")
        loginWindow_emp.resize(362, 283)
        self.centralwidget = QtWidgets.QWidget(loginWindow_emp)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 60, 189, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 200, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 100, 189, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 140, 189, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        loginWindow_emp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(loginWindow_emp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 21))
        self.menubar.setObjectName("menubar")
        loginWindow_emp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(loginWindow_emp)
        self.statusbar.setObjectName("statusbar")
        loginWindow_emp.setStatusBar(self.statusbar)

        self.retranslateUi(loginWindow_emp)
        QtCore.QMetaObject.connectSlotsByName(loginWindow_emp)

    def retranslateUi(self, loginWindow_emp):
        _translate = QtCore.QCoreApplication.translate
        loginWindow_emp.setWindowTitle(_translate("loginWindow_emp", "MainWindow"))
        self.label_2.setText(_translate("loginWindow_emp", "Enter Employee ID:"))
        self.label_5.setText(_translate("loginWindow_emp", "Enter Password:"))
        self.pushButton.setText(_translate("loginWindow_emp", "login in"))
        self.pushButton_2.setText(_translate("loginWindow_emp", "cancel"))
        self.label_3.setText(_translate("loginWindow_emp", "Enter E-Mail Id:"))
        self.label_4.setText(_translate("loginWindow_emp", "Login In"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindow_emp = QtWidgets.QMainWindow()
    ui = Ui_loginWindow_emp()
    ui.setupUi(loginWindow_emp)
    loginWindow_emp.show()
    sys.exit(app.exec_())
