# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signUpWindow_emp(object):
    def setupUi(self, signUpWindow_emp):
        signUpWindow_emp.setObjectName("signUpWindow_emp")
        signUpWindow_emp.resize(360, 334)
        self.centralwidget = QtWidgets.QWidget(signUpWindow_emp)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 270, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 140, 189, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 270, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 60, 189, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 100, 189, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 220, 189, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 180, 189, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 94, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        signUpWindow_emp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(signUpWindow_emp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        signUpWindow_emp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(signUpWindow_emp)
        self.statusbar.setObjectName("statusbar")
        signUpWindow_emp.setStatusBar(self.statusbar)

        self.retranslateUi(signUpWindow_emp)
        QtCore.QMetaObject.connectSlotsByName(signUpWindow_emp)

    def retranslateUi(self, signUpWindow_emp):
        _translate = QtCore.QCoreApplication.translate
        signUpWindow_emp.setWindowTitle(_translate("signUpWindow_emp", "signUpWindow_emp"))
        self.label_3.setText(_translate("signUpWindow_emp", "Enter E-Mail Id:"))
        self.pushButton.setText(_translate("signUpWindow_emp", "Register"))
        self.label_5.setText(_translate("signUpWindow_emp", "Create Password:"))
        self.pushButton_2.setText(_translate("signUpWindow_emp", "cancel"))
        self.label_2.setText(_translate("signUpWindow_emp", "Enter Employee ID:"))
        self.label_4.setText(_translate("signUpWindow_emp", "Sign Up"))
        self.label.setText(_translate("signUpWindow_emp", "Enter  Name:"))
        self.label_6.setText(_translate("signUpWindow_emp", "Confirm Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signUpWindow_emp = QtWidgets.QMainWindow()
    ui = Ui_signUpWindow_emp()
    ui.setupUi(signUpWindow_emp)
    signUpWindow_emp.show()
    sys.exit(app.exec_())
